baseURL = "https://woowa-techcamp-2024.github.io/"
languageCode = "ko-kr"
title = "우아한 테크캠프 기술블로그"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
publishdir = "docs"

[params]
    favicon = "/images/favicon.png"
    avatar = "/images/woowa.png"
    headerIcon = "/images/woowacon.png"